version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8085:8085"
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=todo
    ports:
      - "3306:3306"
